# Generated by Django 3.2.7 on 2021-10-31 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='demo_image',
        ),
        migrations.AlterField(
            model_name='housing',
            name='listing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
