# Generated by Django 3.2.8 on 2021-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20211031_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
