# Generated by Django 3.2.7 on 2021-11-11 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_rename_housing_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
        migrations.AddField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='housing.listing'),
            preserve_default=False,
        ),
    ]
