
# Generated by Django 3.2.7 on 2021-11-14 19:26

# Generated by Django 3.2.7 on 2021-11-13 03:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20211111_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
