# Generated by Django 3.2.7 on 2021-11-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
