# Generated by Django 3.2.7 on 2021-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
