# Generated by Django 3.2.7 on 2021-11-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_auto_20211114_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
