# Generated by Django 3.2.7 on 2021-11-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
